//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantryParty.Models
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RecipeIngredient
    {
        public string RecipeID { get; set; }
        public string IngredientID { get; set; }
        public int keyvalue { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recipe Recipe { get; set; }

        // Checks if the ingredients for each returned recipe are in the DB
        // If not, adds them and the Recipe-Ingredient relationship
        public static void SaveNewRecipeIngredient(JObject IngArray, Recipe ThisRecipe)
        {
            pantrypartyEntities ORM = new pantrypartyEntities();
            if (ORM.Recipes.Find(ThisRecipe.ID) == null)
            {
                ORM.Recipes.Add(ThisRecipe);
                ORM.SaveChanges();
            }
            for (int i = 0; i < IngArray["extendedIngredients"].Count(); i++)
            {
                if (ORM.Ingredients.Find(IngArray["extendedIngredients"][i]["name"].ToString()) == null)
                {
                    Ingredient newIngredient = new Ingredient
                    {
                        Name = IngArray["extendedIngredients"][i]["name"].ToString()
                    };
                    ORM.Ingredients.Add(newIngredient);
                    ORM.SaveChanges();
                }
                RecipeIngredient ObjToCheck = new RecipeIngredient();
                ObjToCheck.RecipeID = ThisRecipe.ID;
                ObjToCheck.IngredientID = IngArray["extendedIngredients"][i]["name"].ToString();
                if (ORM.RecipeIngredients.Where(x => x.RecipeID == ObjToCheck.RecipeID).ToList().Count == 0)
                {
                    ORM.Recipes.Find(ThisRecipe.ID).RecipeIngredients.Add(ObjToCheck);
                    ORM.SaveChanges();
                }
            }
        }
    }
}
