//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantryParty.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Newtonsoft.Json.Linq;

    public partial class UserIngredient
    {
        public string UserID { get; set; }
        public string IngredientID { get; set; }
        public int keyvalue { get; set; }

        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Ingredient Ingredient { get; set; }

        public static List<AspNetUser> FindUsersWith(List<Ingredient> RecipeIngredients, List<Ingredient> UserIngredients)
        {
            pantrypartyEntities ORM = new pantrypartyEntities();
            List<UserIngredient> UIList = new List<UserIngredient>();
            List<AspNetUser> ToReturn = new List<AspNetUser>();

            foreach (var ing in UserIngredients)
            {
                if (RecipeIngredients.Contains(ing))
                {
                    RecipeIngredients.Remove(ing);
                }
            }

            foreach (var ing in RecipeIngredients)
            {
                UIList = ORM.UserIngredients.Where(x => x.IngredientID == ing.Name).ToList();

                if (UIList == null)
                {
                    continue;
                }
                foreach (var item in UIList)
                {
                    ToReturn.AddRange(ORM.AspNetUsers.Where(x => x.ID == item.UserID).ToList());
                }
            }
            ToReturn.Distinct<AspNetUser>().ToList();
            return ToReturn;
        }

        public static void SaveNewRecipeIngredient(JObject IngArray, Recipe ThisRecipe)
        {
            pantrypartyEntities ORM = new pantrypartyEntities();
            if (ORM.Recipes.Find(ThisRecipe.ID) == null)
            {
                ORM.Recipes.Add(ThisRecipe);
                ORM.SaveChanges();
            }

            for (int i = 0; i < IngArray["extendedIngredients"].Count(); i++)
            {
                if (ORM.Ingredients.Find(IngArray["extendedIngredients"][i]["name"].ToString()) == null)
                {
                    Ingredient newIngredient = new Ingredient
                    {
                        Name = IngArray["extendedIngredients"][i]["name"].ToString()
                    };
                    ORM.Ingredients.Add(newIngredient);
                    ORM.SaveChanges();
                }

                RecipeIngredient ObjToCheck = new RecipeIngredient
                {
                    RecipeID = ThisRecipe.ID,
                    IngredientID = IngArray["extendedIngredients"][i]["name"].ToString()
                };

                if (ORM.RecipeIngredients.Where(x => x == ObjToCheck) == null)
                {
                    ORM.RecipeIngredients.Add(ObjToCheck);
                    ORM.SaveChanges();
                }
            }
        }
    }
}
